docker:
  image: yegor256/rultor-image:1.13.0
install: |-
  sudo apt-get install -y python3-pygments
  sudo pip3 install pygments
  sudo tlmgr option repository ctan
  sudo gem install texsc:0.6.0
  sudo gem install texqc:0.6.0
  sudo apt-get install -y aspell
  sudo tlmgr --verify-repo=none update --self
  sudo tlmgr --verify-repo=none install l3build
release:
  script: |-
    make VERSION=${tag} set-version
    git commit -am "version set to ${tag}"
    make
    echo 'y' | l3build upload --halt-on-error
