name: l3build
on:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  l3build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: yegor256/qpdf-action@master
      - uses: teatimeguest/setup-texlive-action@v3.2.1
        with:
          update-all-packages: true
          package-file: DEPENDS.txt
      - run: l3build check -q --show-log-on-error

