# (The MIT License)
#
# Copyright (c) 2021-2024 Yegor Bugayenko
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the 'Software'), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
name: l3build
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  l3build:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm-256color
    strategy:
      matrix:
        os: [ubuntu-24.04]
    steps:
      - uses: actions/checkout@v4
      - uses: yegor256/qpdf-action@master
      - run: sudo apt-get -y install ghostscript
        if: matrix.os == 'ubuntu-24.04'
      - uses: teatimeguest/setup-texlive-action@v3.3.4
        with:
          update-all-packages: true
          package-file: DEPENDS.txt
      - run: l3build ctan --show-log-on-error --halt-on-error
      - run: |
          mkdir build/gh-pages
          cp build/distrib/tds/tex/latex/kdpcover/kdpcover.cls build/gh-pages
          sed -i "s/0\.0\.0/$(date +%H.%M.%S)/g" build/gh-pages/kdpcover.cls
          sed -i "s|0000/00/00|$(date +%Y/%m/%d)|g" build/gh-pages/kdpcover.cls
        if: github.ref == 'refs/heads/master' && matrix.os == 'ubuntu-24.04'
      - uses: JamesIves/github-pages-deploy-action@v4.7.2
        with:
          branch: gh-pages
          folder: build/gh-pages
          clean: true
        if: github.ref == 'refs/heads/master' && matrix.os == 'ubuntu-24.04'
